---
name: License report action test

on:
  pull_request:
    branches:
      - main

jobs:
  aragog:
    runs-on: ubuntu-latest
    name: Test aragog

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: License report
        uses: ./r-license-report
        with:
          path: ./tests/packages/aragog

  buckbeak:
    runs-on: ubuntu-latest
    name: Test buckbeak

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: License report
        uses: ./r-license-report
        with:
          path: ./tests/packages/buckbeak
          regex: "GPL.*"
          fail: true
          mran_snapshot_date: "2021-01-01"
          bioc_release: "3.13"
